[project]
name = "mcp-cilent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.122.0",
    "fastmcp>=2.13.1",
    "mcp>=1.22.0",
    "python-dotenv>=1.2.1",
    "sap-ai-sdk-gen>=5.8.0",
]
